"""Robot Framework keyword library for the Order Management docs capture suite.

Reads the doc site's docs/screenshot-manifest.json (generated by docs/scripts/build-site.js)
and gives the .robot suite the list of shots to take, plus small helpers for resolving
record URLs and locating the output docs/images/ folder. Keeping this logic in Python
keeps the .robot files readable.
"""
import json
import os
import re
from urllib.parse import urlparse

from robot.api.deco import keyword, library


@library(scope="GLOBAL")
class DocsCapture:
    ROBOT_LIBRARY_VERSION = "1.0"

    def __init__(self):
        here = os.path.dirname(os.path.abspath(__file__))
        # resources -> OrderDemo -> robot -> robot-capture -> <sf-docs-automation-demo root>
        self.site_root = os.path.abspath(os.path.join(here, "..", "..", "..", ".."))
        self.manifest_path = os.path.join(self.site_root, "docs", "screenshot-manifest.json")
        self.images_dir = os.path.join(self.site_root, "docs", "images")

    @keyword
    def load_manifest(self):
        """Return the full list of screenshot entries from docs/screenshot-manifest.json."""
        with open(self.manifest_path, encoding="utf-8") as fh:
            return json.load(fh)

    @keyword
    def navigable_screenshots(self):
        """Entries that can be captured by navigating to a URL (have a url_pattern).

        This covers the large majority — including record pages, whose ``{recordId}``
        is resolved at run time via a SOQL query. Shots that need genuine multi-step
        interaction (App Launcher, filling in a New Order form) still have a
        url_pattern here as a navigable fallback, but their own dedicated test case
        (run afterwards, in docs_capture.robot) overwrites the image with the real
        interactive capture.
        """
        return [s for s in self.load_manifest() if s.get("url_pattern")]

    @keyword
    def images_dir_path(self):
        """Absolute path to docs/images/ (created if missing)."""
        os.makedirs(self.images_dir, exist_ok=True)
        return self.images_dir

    @keyword
    def object_api_name(self, url_pattern):
        """Pull the object API name out of a /lightning/r/<Object>/{recordId}/... pattern."""
        m = re.search(r"/lightning/r/([^/]+)/", url_pattern or "")
        return m.group(1) if m else ""

    @keyword
    def origin_of(self, url):
        """Return scheme://host for a full URL (used to derive the org base URL)."""
        p = urlparse(url)
        return f"{p.scheme}://{p.netloc}"
